/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Hospital } from "./Hospital";
import { HospitalCountArgs } from "./HospitalCountArgs";
import { HospitalFindManyArgs } from "./HospitalFindManyArgs";
import { HospitalFindUniqueArgs } from "./HospitalFindUniqueArgs";
import { CreateHospitalArgs } from "./CreateHospitalArgs";
import { UpdateHospitalArgs } from "./UpdateHospitalArgs";
import { DeleteHospitalArgs } from "./DeleteHospitalArgs";
import { AppointmentFindManyArgs } from "../../appointment/base/AppointmentFindManyArgs";
import { Appointment } from "../../appointment/base/Appointment";
import { LocationFindManyArgs } from "../../location/base/LocationFindManyArgs";
import { Location } from "../../location/base/Location";
import { HospitalService } from "../hospital.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Hospital)
export class HospitalResolverBase {
  constructor(
    protected readonly service: HospitalService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Hospital",
    action: "read",
    possession: "any",
  })
  async _hospitalsMeta(
    @graphql.Args() args: HospitalCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Hospital])
  @nestAccessControl.UseRoles({
    resource: "Hospital",
    action: "read",
    possession: "any",
  })
  async hospitals(
    @graphql.Args() args: HospitalFindManyArgs
  ): Promise<Hospital[]> {
    return this.service.hospitals(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Hospital, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Hospital",
    action: "read",
    possession: "own",
  })
  async hospital(
    @graphql.Args() args: HospitalFindUniqueArgs
  ): Promise<Hospital | null> {
    const result = await this.service.hospital(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Hospital)
  @nestAccessControl.UseRoles({
    resource: "Hospital",
    action: "create",
    possession: "any",
  })
  async createHospital(
    @graphql.Args() args: CreateHospitalArgs
  ): Promise<Hospital> {
    return await this.service.createHospital({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Hospital)
  @nestAccessControl.UseRoles({
    resource: "Hospital",
    action: "update",
    possession: "any",
  })
  async updateHospital(
    @graphql.Args() args: UpdateHospitalArgs
  ): Promise<Hospital | null> {
    try {
      return await this.service.updateHospital({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Hospital)
  @nestAccessControl.UseRoles({
    resource: "Hospital",
    action: "delete",
    possession: "any",
  })
  async deleteHospital(
    @graphql.Args() args: DeleteHospitalArgs
  ): Promise<Hospital | null> {
    try {
      return await this.service.deleteHospital(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Appointment], { name: "appointments" })
  @nestAccessControl.UseRoles({
    resource: "Appointment",
    action: "read",
    possession: "any",
  })
  async findAppointments(
    @graphql.Parent() parent: Hospital,
    @graphql.Args() args: AppointmentFindManyArgs
  ): Promise<Appointment[]> {
    const results = await this.service.findAppointments(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Location], { name: "locations" })
  @nestAccessControl.UseRoles({
    resource: "Location",
    action: "read",
    possession: "any",
  })
  async findLocations(
    @graphql.Parent() parent: Hospital,
    @graphql.Args() args: LocationFindManyArgs
  ): Promise<Location[]> {
    const results = await this.service.findLocations(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
