/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Otp as PrismaOtp, User as PrismaUser } from "@prisma/client";

export class OtpServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.OtpCountArgs, "select">): Promise<number> {
    return this.prisma.otp.count(args);
  }

  async otps(args: Prisma.OtpFindManyArgs): Promise<PrismaOtp[]> {
    return this.prisma.otp.findMany(args);
  }
  async otp(args: Prisma.OtpFindUniqueArgs): Promise<PrismaOtp | null> {
    return this.prisma.otp.findUnique(args);
  }
  async createOtp(args: Prisma.OtpCreateArgs): Promise<PrismaOtp> {
    return this.prisma.otp.create(args);
  }
  async updateOtp(args: Prisma.OtpUpdateArgs): Promise<PrismaOtp> {
    return this.prisma.otp.update(args);
  }
  async deleteOtp(args: Prisma.OtpDeleteArgs): Promise<PrismaOtp> {
    return this.prisma.otp.delete(args);
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.otp
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
